version: '3'

networks:
  network_saga_comunication:
    external: true

services:
  car-rental-db:
    image: mongo:3.4
  car-rental-app:
    image: node:8.1
    volumes:
      - ./car-rental-service:/backend
    ports:
      - 7272:7272
    command: bash -c "cd /backend && npm i && npm install -g nodemon && nodemon app.js"
    networks:
      - default
      - network_saga_comunication