version: '3'
networks:
  network_saga_comunication:
    external: true

services:
  travel-app:
    image: node:8.1
    volumes:
      - ./travel-service:/backend
    ports:
      - 8080:8080
    command: bash -c "cd /backend && npm i && npm install -g nodemon && nodemon app.js"
    networks:
      - network_saga_comunication
  
  travel-front:
    image: nginx:1.13
    volumes:
      - ./travel-front:/usr/share/nginx/html/
    ports:
      - 8181:80
