version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes:
      - ./credit-service:/backend
    ports:
      - 7178:7178
    command: bash -c "cd /backend && npm i && npm install -g nodemon && nodemon app.js"