version: '3'

networks:
  network_saga_comunication:
    external: true

services:
  hotel-booking-db:
    image: mongo:3.4
  hotel-booking-app:
    image: node:8.1
    volumes:
      - ./hotel-booking-service:/backend
    ports:
      - 7171:7171
    command: bash -c "cd /backend && npm i && npm install -g nodemon && nodemon app.js"
    networks:
      - default
      - network_saga_comunication
  frontend:
    image: nginx:1.13
    volumes:
      - ./hotel-booking-front:/usr/share/nginx/html/
    ports:
      - 7172:80